# Generated by Django 3.1.7 on 2021-04-19 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=132)),
                ('authorization', models.CharField(max_length=64, unique=True)),
                ('code_auth', models.CharField(max_length=6, null=True)),
                ('is_sms', models.BooleanField(default=False)),
                ('is_email', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('check', models.DateTimeField(default=datetime.datetime(2021, 4, 19, 21, 39, 38, 57617))),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2021, 4, 19, 21, 39, 38, 57617))),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('type_project', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
