# Generated by Django 3.1.7 on 2021-04-02 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=132)),
                ('authorization', models.TextField(null=True)),
                ('code_auth', models.CharField(max_length=6, null=True)),
                ('is_sms', models.BooleanField(default=False)),
                ('is_email', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('check', models.DateTimeField(default=datetime.datetime(2021, 4, 2, 21, 12, 52, 456054))),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2021, 4, 2, 21, 12, 52, 456054))),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=64)),
                ('inn', models.CharField(max_length=32)),
                ('link', models.TextField()),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
