# Generated by Django 3.1.7 on 2021-04-10 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='check',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 20, 8, 11, 625977)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 20, 8, 11, 625977)),
        ),
    ]
