# Generated by Django 3.1.7 on 2021-04-29 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210428_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countfavoriteproj',
            old_name='count',
            new_name='_count',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='check',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 21, 39, 6, 850586)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 21, 39, 6, 850586)),
        ),
    ]
